### ISSUE TITLE
Yo bro make one for slash

### ISSUE THREAD

**Issue by SummerToast** [vKxni/disco.js#2]
Can you make one for slash? with options PLEASE

**Comment by vKxni** [comment]
Which one are you looking for?

**Comment by SummerToast** [comment]
The premium system and i get lots of errors and i just deleted it bc im waiting for your slash :)) btw tell me your discord

**Comment by vKxni** [comment]
The code is working just fine - and according to the feedback it also works fine for other people. You can easily port it over to slash commands by following the official Discord.js Guide. 
FYI: message commands still work.

**Comment by SummerToast** [comment]
im trying to hard to make it slash but its too hard :(
